<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php
/** @var \Sigma\PriceMatrix\ViewModel\ProductsList $block */
$viewModel = $block->getData("view_model");
?>
<?php
$isPriceMatrixAvailable = $viewModel->isPriceMatrixAvailable($_product->getId());
$priceMatrixModel = $viewModel->getPriceMatrixModel();

?>
<?php if ($_product->isSaleable() && $isPriceMatrixAvailable):?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()):?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <?php $i = 1;?>
                <?php if ($isPriceMatrixAvailable && $priceMatrixModel->getData('checkbox_' . $i) == 1):?>
                    <button type="submit"
                            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?= $block->escapeHtml($buttonTitle) ?></span>
                    </button>
                <?php endif; ?>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
